- hosts: datanode
  tasks:
   - name: "Transferring Java software"
     copy:
      src: "/root/jdk-8u171-linux-x64.rpm"
      dest: "/root"

   - name: "Transferring hadoop software"
     copy:
      src: "/root/hadoop-1.2.1-1.x86_64.rpm"
      dest: "/root/"

   - name: "Installing hadoop"
     command: "rpm -ivh hadoop-1.2.1-1.x86_64.rpm --force"
     ignore_errors: yes

   - name: "Installing java"
     command: "rpm -ivh jdk-8u171-linux-x64.rpm"
     ignore_errors: yes

   - name: "Creating Data node directory"
     file:
      path: /datanode
      state: directory
     ignore_errors: yes

   - name: "configuring hdfs-site.xml"
     template:
      dest: /etc/hadoop/hdfs-site.xml
      src: /root/ansible/datanode/hdfs-site.xml

   - name: "Configuring core-site.xml"
     template:
      dest: /etc/hadoop/core-site.xml
      src: /root/ansible/datanode/core-site.xml

   - name: "Starting hadoop services for data node"
     command: "hadoop-daemon.sh start datanode"
     register: service
   - debug:
           var: service

   - name: "Checking the status of data node"
     command: "jps"
     register: jps
   - debug:
           var: jps.stdout_lines
